--[[
    dps-clothingbrowser Server
    Handles outfit export file saving (JSON + wasabi Lua format)
]]

-- Convert a parsed outfit table to a wasabi-formatted Lua string
-- ready to paste into wasabi_police/wasabi_ambulance config.lua uniforms table
local function ConvertToWasabi(data)
    local label = data.label or 'Unnamed Outfit'
    local modelStr = data.model or 'mp_m_freemode_01'
    local isMale = modelStr == 'mp_m_freemode_01'
    local gender = isMale and 'male' or 'female'

    -- Determine minGrade
    local minGrade = 0
    if data.grades and #data.grades > 0 then
        minGrade = data.grades[1]
        for _, g in ipairs(data.grades) do
            if g < minGrade then minGrade = g end
        end
    end

    -- Build clothing lines (components -> clothing, component_id -> component)
    local clothingLines = {}
    if data.components then
        for _, c in ipairs(data.components) do
            table.insert(clothingLines, string.format(
                '                { component = %d, drawable = %d, texture = %d },',
                c.component_id, c.drawable, c.texture
            ))
        end
    end

    -- Build prop lines (prop_id -> component)
    local propLines = {}
    if data.props then
        for _, p in ipairs(data.props) do
            table.insert(propLines, string.format(
                '                { component = %d, drawable = %d, texture = %d },',
                p.prop_id, p.drawable, p.texture
            ))
        end
    end

    -- Assemble the Lua table
    local otherGender = isMale and 'female' or 'male'

    local lines = {}
    table.insert(lines, '    {')
    table.insert(lines, string.format("        label = '%s',", label:gsub("'", "\\'")))
    table.insert(lines, string.format('        minGrade = %d,', minGrade))

    -- Active gender block
    table.insert(lines, string.format('        %s = {', gender))
    table.insert(lines, '            clothing = {')
    for _, line in ipairs(clothingLines) do
        table.insert(lines, line)
    end
    table.insert(lines, '            },')
    table.insert(lines, '            props = {')
    for _, line in ipairs(propLines) do
        table.insert(lines, line)
    end
    table.insert(lines, '            },')
    table.insert(lines, '        },')

    -- Other gender placeholder
    table.insert(lines, string.format('        %s = {', otherGender))
    table.insert(lines, '            clothing = {')
    table.insert(lines, '                -- TODO: export this gender from the clothing browser')
    table.insert(lines, '            },')
    table.insert(lines, '            props = {')
    table.insert(lines, '            },')
    table.insert(lines, '        },')

    table.insert(lines, '    },')

    return table.concat(lines, '\n')
end

lib.callback.register('dps-clothingbrowser:saveExport', function(source, jsonStr, name)
    local safeName = (name or 'outfit'):gsub('[^%w%-_]', '_')
    local timestamp = os.date('%Y%m%d_%H%M%S')
    local jsonFilename = string.format('exports/%s_%s.json', safeName, timestamp)

    local success = SaveResourceFile(GetCurrentResourceName(), jsonFilename, jsonStr, -1)

    if success then
        local playerName = GetPlayerName(source) or 'Unknown'
        print(string.format('[dps-clothingbrowser] %s exported outfit: %s', playerName, jsonFilename))

        -- Also generate wasabi Lua format
        local parsed = json.decode(jsonStr)
        if parsed then
            local wasabiLua = ConvertToWasabi(parsed)
            local header = string.format(
                '-- Wasabi uniform entry generated by dps-clothingbrowser\n'
                .. '-- Source: %s\n'
                .. '-- Paste this into your wasabi_police or wasabi_ambulance config.lua uniforms table\n\n',
                jsonFilename
            )
            local luaFilename = string.format('wasabi-exports/%s_%s.lua', safeName, timestamp)
            local luaSuccess = SaveResourceFile(GetCurrentResourceName(), luaFilename, header .. wasabiLua, -1)
            if luaSuccess then
                print(string.format('[dps-clothingbrowser] Wasabi format saved: %s', luaFilename))
            end
        end

        return jsonFilename
    end

    return nil
end)
